clone:
  depth: full

definitions:
  caches:
    sonar: ~/.sonar/cache
  steps:
    - step: &sonar-backend
        name: Build, test and analyze on SonarQube Cloud
        image: gradle:jdk21
        caches:
          - gradle
          - sonar
        script:
          - ./gradlew test --continue jacocoTestReport sonar
        artifacts:
          - build/libs/**
    - step: &sonar-frontend
        name: Build, test and analyze on SonarQube Cloud
        image: node:22
        caches:
          - node
          - sonar
        script:
          - cd frontend
          - npm ci
          - npm run test --
            --run --coverage
            --reporter=junit --outputFile=coverage/junit-report.xml
            --reporter=default
            || touch coverage/testfail
          - pipe: sonarsource/sonarcloud-scan:4.0.0
            variables:
              SONAR_TOKEN: $SONAR_TOKEN_FRONT
              EXTRA_ARGS:
                - '-Dsonar.projectKey=matarillo-bitbucket_flaskr-frontend'
                - '-Dsonar.organization=matarillo-bitbucket'
                - '-Dsonar.javascript.lcov.reportPaths=coverage/lcov.info'
          - |
            if [ -f coverage/testfail ]; then
              echo "Vitest failed."
              exit 1
            fi
        artifacts:
          - frontend/coverage/**

pipelines:
  custom:
    sonar-backend:
      - step: *sonar-backend
    sonar-frontend:
      - step: *sonar-frontend
